-- MySQL Script generated by MySQL Workbench
-- Sat Feb 20 21:26:56 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MOVIE_FLIX
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MOVIE_FLIX` ;

-- -----------------------------------------------------
-- Schema MOVIE_FLIX
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MOVIE_FLIX` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `MOVIE_FLIX` ;

-- -----------------------------------------------------
-- Table `MOVIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOVIE` (
  `movie_id` INT NOT NULL COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `year` SMALLINT NULL COMMENT '',
  `rated` VARCHAR(45) NULL COMMENT '',
  `runtime` VARCHAR(45) NULL COMMENT '',
  `plot` TEXT NULL COMMENT '',
  `language` VARCHAR(30) NULL COMMENT '',
  `country` VARCHAR(45) NULL COMMENT '',
  `awards` VARCHAR(300) NULL COMMENT '',
  `poster` VARCHAR(300) NULL COMMENT '',
  `metascore` SMALLINT NULL COMMENT '',
  `imdb_rating` DECIMAL(3,1) NULL COMMENT '',
  `imdb_votes` INT NULL COMMENT '',
  `imdb_id` VARCHAR(20) NULL COMMENT '',
  `movie_flix_rating` DECIMAL(3,1) NULL COMMENT '',
  PRIMARY KEY (`movie_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `VIDEO_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VIDEO_TYPE` (
  `video_type_id` INT NOT NULL COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`video_type_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MOVIE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOVIE_TYPE` (
  `movie_id` INT NOT NULL COMMENT '',
  `video_type_id` INT NOT NULL COMMENT '',
  INDEX `video_type_id_idx` (`video_type_id` ASC)  COMMENT '',
  CONSTRAINT `fk_movie_type_movieid`
    FOREIGN KEY (`movie_id`)
    REFERENCES `MOVIE` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_type_videotypeid`
    FOREIGN KEY (`video_type_id`)
    REFERENCES `VIDEO_TYPE` (`video_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GENRE` (
  `genre_id` INT NOT NULL COMMENT '',
  `type` VARCHAR(75) NULL COMMENT '',
  PRIMARY KEY (`genre_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MOVIE_GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOVIE_GENRE` (
  `movie_id` INT NOT NULL COMMENT '',
  `genre_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`movie_id`, `genre_id`)  COMMENT '',
  INDEX `genre_id_idx` (`genre_id` ASC)  COMMENT '',
  CONSTRAINT `fk_movie_genre_movieid`
    FOREIGN KEY (`movie_id`)
    REFERENCES `MOVIE` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_genre_genreid`
    FOREIGN KEY (`genre_id`)
    REFERENCES `GENRE` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MOVIE_VIDEO_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOVIE_VIDEO_TYPE` (
  `movie_id` INT NOT NULL COMMENT '',
  `video_type_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`movie_id`, `video_type_id`)  COMMENT '',
  INDEX `video_type_id_idx` (`video_type_id` ASC)  COMMENT '',
  CONSTRAINT `movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `MOVIE` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `video_type_id`
    FOREIGN KEY (`video_type_id`)
    REFERENCES `VIDEO_TYPE` (`video_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROLE` (
  `role_id` INT NOT NULL COMMENT '',
  `role_type` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`role_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CREW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CREW` (
  `crew_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(80) NOT NULL COMMENT '',
  `role_id` INT NULL COMMENT '',
  PRIMARY KEY (`crew_id`)  COMMENT '',
  INDEX `role_id_idx` (`role_id` ASC)  COMMENT '',
  CONSTRAINT `fk_crew_roleid`
    FOREIGN KEY (`role_id`)
    REFERENCES `ROLE` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MOVIE_CREW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOVIE_CREW` (
  `movie_id` INT NOT NULL COMMENT '',
  `crew_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`movie_id`, `crew_id`)  COMMENT '',
  INDEX `crew_id_idx` (`crew_id` ASC)  COMMENT '',
  CONSTRAINT `fk_movie_crew_movieid`
    FOREIGN KEY (`movie_id`)
    REFERENCES `MOVIE` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_crew_crewid`
    FOREIGN KEY (`crew_id`)
    REFERENCES `CREW` (`crew_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USER_ROLE` (
  `user_role_id` INT NOT NULL COMMENT '',
  `role_desc` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`user_role_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USER` (
  `user_id` VARCHAR(60) NOT NULL COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `email_id` VARCHAR(45) NULL COMMENT '',
  `password_hash` VARCHAR(75) NULL COMMENT '',
  `user_role_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  INDEX `fk_user_userroleid_idx` (`user_role_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_userroleid`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `USER_ROLE` (`user_role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USER_MOVIE_COMMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USER_MOVIE_COMMENTS` (
  `user_movie_comments_id` INT NOT NULL COMMENT '',
  `user_id` VARCHAR(60) NOT NULL COMMENT '',
  `movie_id` INT NOT NULL COMMENT '',
  `comment` TEXT NULL COMMENT '',
  PRIMARY KEY (`user_movie_comments_id`)  COMMENT '',
  INDEX `fk_user_movie_comments_movie_id_idx` (`movie_id` ASC)  COMMENT '',
  INDEX `fk_user_movie_comments_userid_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_movie_comments_movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `MOVIE` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_movie_comments_userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `USER` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
